### PR TITLE
feat: add support for one-time (creation-time) bindings

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
This PR adds a new instruction for one-time (creation-time) bindings. The idea is that for case like:
`[prop]="::exp"` (syntax to be defined) it would generate:
`p('prop', o(cm && exp))`.

I was hesitating if a new instruction is warranted here (we could simply do `p('prop', cm ? exp : NO_CHANGE))`, but with a new instruction we've got less code to generate.

This PR should cover all the following binding cases:
* property: `[foo]="::exp"` => `p('foo', o(cm && exp))`
* attribute: `[attr.foo]="::exp"` => `a('foo', o(cm && exp))`
* class: `[class.foo]="::exp"` => `c('foo', o(cm && exp))`
* style: `[style.foo.px]="::exp"` => `s('foo', o(cm && exp), 'px')`

Support for interpolations and directive inputs in a separate PR.

### CODE REVIEW

**Comment by benouat** [comment]
I don't really see the added value of the `&&` outside to then do it somehow again inside...
What about this:

```javascript
p('foo', o(cm, exp));
```

```javascript
function bindOnce(cm, exp) { return (cm && exp) || NO_CHANGE ; }
```

**Comment by pkozlowski-opensource** [comment]
> `p('foo', o(cm, exp));`

This wouldn't work as `exp` would be evaluated all the time. We need to guard this expression not only to prevent DOM updates but also to make sure that expressions are not evaluated when not necessary. This is what this test is all about:  https://github.com/mhevery/ngiv/pull/24/files#diff-b17322378a31747eab7b4d0751c056faR214

**Comment by benouat** [comment]
> This is what this test is all about: https://github.com/mhevery/ngiv/pull/24/files#diff-b17322378a31747eab7b4d0751c056faR214

But your test  is using a method which reuse `cm`. To me your test does not test at all the case `cm && exp`.

When you access `exp` as an argument of the `o()` function, it’s a local variable to the template function, it already has been evaluated.

I get your point of not re-evaluating the expression, but to me here, it does not prevent it. Your test does not even verify that to me.

**Comment by pkozlowski-opensource** [comment]
> When you access exp as an argument of the o() function, it’s a local variable to the template function, it already has been evaluated.

@benouat not sure what you mean here... We've got 2 cases:
* `cm` is `true` => argument of the `o` function will be equal to `exp`
* `cm` is `false` =>argument of the `o` function will be equal to `false` and `exp` will _not_ be evaluated

Of course it _might_ happen that `exp` is a local template variable but:
* we don't have such a case till we fully support JS in template functions;
* users _must_ understand that template functions are executed on each change detection and act accordingly.

I've also changed the test to make it, hopefully, more clear.

**Comment by benouat** [comment]
@pkozlowski-opensource ok then, if you externalise the extensive computation to a function, that's fine. 

My concern was more in case of accessing a direct reference to 'something big'. If you access a direct reference, it will be evaluated when executing `Template(... , ...)`.
If the direct reference is a getter function, where expensive computation are done, same issue. You won't prevent the evaluation with a simple `&&`

To be sure to prevent it each time, we could simply make sure that this explique is attach on a parent object when we call it inside `o( cm && parent.expr )`. This is the only way to manage the `getter` use case to me.

> users must understand that template functions are executed on each change detection and act accordingly.

I agree & disagree. It's good to understand everything behind the hood, because you cam learn a lot from it.
But you might also want to rely on a framework for the exact opposite reason, you might not want to have to think about such thing. The framework should be handling it for you.

Nonetheless, here it's just discussion and thinking. I am fine for now with the change otherwise.

**Comment by pkozlowski-opensource** [comment]
@benouat of course that users can always do something expensive and we can't prevent everything. The primary use-case for this PR is sth like `<input [placeholder]="expensiveLocalizationCall(localizationKey)"`>

**Comment by mhevery** [comment]
I am a bit confused why this is needed. Isn't it just:

property:` [foo]`="::exp" => cm && p('foo', b(exp))
attribute: `[attr.foo]`="::exp" => cm && a('foo', b(exp))
class: `[class.foo]`="::exp" => cm && c('foo', b(exp))
style: `[style.foo.px]`="::exp" => cm && s('foo', b(exp), 'px')


I don't think anything is needed, it is just a matter of generating the right code.

**Comment by pkozlowski-opensource** [comment]
Using b() would mean storing an old value even if we don't need it for future comparisons, this why I've introduced o(). But we can definitivelly go with you approach if we don't care anout this additional memory usage. I llike your approach sine it would skip function calls in the update mode altogether.

**Comment by pkozlowski-opensource** [comment]
Closing this one in favour of #52

**Pull request closed without merging**
